//generated by Precompiler.ipynb on 2018-02-22 16:38:35.160537
#include "CR_precomp.h"

#include <math.h>

    void alloc_cr_input_data(cr_input_data *bb){
    bb->dihed_angles = gsl_vector_alloc(7);
    bb->bend_angles  = gsl_vector_alloc(7);
    bb->r            = gsl_vector_alloc(7);
    bb->d            = gsl_vector_alloc(3);
}

void free_cr_input_data(cr_input_data *bb){
    gsl_vector_free( bb->dihed_angles );
    gsl_vector_free( bb->bend_angles  );
    gsl_vector_free( bb->d            );
    gsl_vector_free( bb->r            );
}

void memcpy_cr_input_data(cr_input_data *bb_a, cr_input_data *bb_b){
    gsl_vector_memcpy ( bb_a->dihed_angles, bb_b->dihed_angles);
    gsl_vector_memcpy ( bb_a->bend_angles , bb_b->bend_angles );
    gsl_vector_memcpy ( bb_a->r           , bb_b->r           );
    gsl_vector_memcpy ( bb_a->d           , bb_b->d           );
}
void T7 (gsl_vector *T,const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    T7_explicit(T,cr_data);
}
int TmT7_t1(gsl_vector *T,const struct cr_input_data bb)
{
    int i,error, sign;
    char err_string[1024];
    double r,theta,alpha,d;
    double x;
    struct expl_data cr_data;
    gsl_matrix *M;
    gsl_vector *V;
    gsl_permutation * p = gsl_permutation_alloc (6);
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    M=jac_explicit_t1( cr_data );
    V=DT7_explicit_t1( cr_data );
    error=gsl_linalg_LU_decomp(M,p,&sign);
    if(error !=GSL_SUCCESS) {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        sprintf(err_string,"GSL failing with error %d\n",error);
        failed(err_string);
    }
    x= gsl_linalg_LU_det(M,sign);
    if (fabs(x) < EPSIL_DET )
    {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_permutation_free(p);
        return -1;
    }else {
        gsl_vector_view  T_ = gsl_vector_subvector (T, 1, 6);
        error=gsl_linalg_LU_solve(M,p,V,&T_.vector);
        
        gsl_vector_set(T,0,-1);
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_vector_scale(T,-1.0);
        gsl_permutation_free(p);
        return error;
    }
}
int TmT7_t2(gsl_vector *T,const struct cr_input_data bb)
{
    int i,error, sign;
    char err_string[1024];
    double r,theta,alpha,d;
    double x;
    struct expl_data cr_data;
    gsl_matrix *M;
    gsl_vector *V;
    gsl_permutation * p = gsl_permutation_alloc (6);
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    M=jac_explicit_t2( cr_data );
    V=DT7_explicit_t2( cr_data );
    error=gsl_linalg_LU_decomp(M,p,&sign);
    if(error !=GSL_SUCCESS) {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        sprintf(err_string,"GSL failing with error %d\n",error);
        failed(err_string);
    }
    x= gsl_linalg_LU_det(M,sign);
    if (fabs(x) < EPSIL_DET )
    {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_permutation_free(p);
        return -1;
    }else {
        gsl_vector_view  T_ = gsl_vector_subvector (T, 1, 6);
        error=gsl_linalg_LU_solve(M,p,V,&T_.vector);
        
        gsl_vector_set(T,0,gsl_vector_get(T,1));
        gsl_vector_set(T,1,-1);
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_vector_scale(T,-1.0);
        gsl_permutation_free(p);
        return error;
    }
}
int TmT7_t3(gsl_vector *T,const struct cr_input_data bb)
{
    int i,error, sign;
    char err_string[1024];
    double r,theta,alpha,d;
    double x;
    struct expl_data cr_data;
    gsl_matrix *M;
    gsl_vector *V;
    gsl_permutation * p = gsl_permutation_alloc (6);
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    M=jac_explicit_t3( cr_data );
    V=DT7_explicit_t3( cr_data );
    error=gsl_linalg_LU_decomp(M,p,&sign);
    if(error !=GSL_SUCCESS) {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        sprintf(err_string,"GSL failing with error %d\n",error);
        failed(err_string);
    }
    x= gsl_linalg_LU_det(M,sign);
    if (fabs(x) < EPSIL_DET )
    {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_permutation_free(p);
        return -1;
    }else {
        gsl_vector_view  T_ = gsl_vector_subvector (T, 1, 6);
        error=gsl_linalg_LU_solve(M,p,V,&T_.vector);
        
        gsl_vector_set(T,0,gsl_vector_get(T,1));
        gsl_vector_set(T,1,gsl_vector_get(T,2));
        gsl_vector_set(T,2,-1);
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_vector_scale(T,-1.0);
        gsl_permutation_free(p);
        return error;
    }
}
int TmT7_t4(gsl_vector *T,const struct cr_input_data bb)
{
    int i,error, sign;
    char err_string[1024];
    double r,theta,alpha,d;
    double x;
    struct expl_data cr_data;
    gsl_matrix *M;
    gsl_vector *V;
    gsl_permutation * p = gsl_permutation_alloc (6);
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    M=jac_explicit_t4( cr_data );
    V=DT7_explicit_t4( cr_data );
    error=gsl_linalg_LU_decomp(M,p,&sign);
    if(error !=GSL_SUCCESS) {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        sprintf(err_string,"GSL failing with error %d\n",error);
        failed(err_string);
    }
    x= gsl_linalg_LU_det(M,sign);
    if (fabs(x) < EPSIL_DET )
    {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_permutation_free(p);
        return -1;
    }else {
        gsl_vector_view  T_ = gsl_vector_subvector (T, 1, 6);
        error=gsl_linalg_LU_solve(M,p,V,&T_.vector);
        
        gsl_vector_set(T,0,gsl_vector_get(T,1));
        gsl_vector_set(T,1,gsl_vector_get(T,2));
        gsl_vector_set(T,2,gsl_vector_get(T,3));
        gsl_vector_set(T,3,-1);
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_vector_scale(T,-1.0);
        gsl_permutation_free(p);
        return error;
    }
}
int TmT7_t5(gsl_vector *T,const struct cr_input_data bb)
{
    int i,error, sign;
    char err_string[1024];
    double r,theta,alpha,d;
    double x;
    struct expl_data cr_data;
    gsl_matrix *M;
    gsl_vector *V;
    gsl_permutation * p = gsl_permutation_alloc (6);
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    M=jac_explicit_t5( cr_data );
    V=DT7_explicit_t5( cr_data );
    error=gsl_linalg_LU_decomp(M,p,&sign);
    if(error !=GSL_SUCCESS) {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        sprintf(err_string,"GSL failing with error %d\n",error);
        failed(err_string);
    }
    x= gsl_linalg_LU_det(M,sign);
    if (fabs(x) < EPSIL_DET )
    {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_permutation_free(p);
        return -1;
    }else {
        gsl_vector_view  T_ = gsl_vector_subvector (T, 1, 6);
        error=gsl_linalg_LU_solve(M,p,V,&T_.vector);
        
        gsl_vector_set(T,0,gsl_vector_get(T,1));
        gsl_vector_set(T,1,gsl_vector_get(T,2));
        gsl_vector_set(T,2,gsl_vector_get(T,3));
        gsl_vector_set(T,3,gsl_vector_get(T,4));
        gsl_vector_set(T,4,-1);
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_vector_scale(T,-1.0);
        gsl_permutation_free(p);
        return error;
    }
}
int TmT7_t6(gsl_vector *T,const struct cr_input_data bb)
{
    int i,error, sign;
    char err_string[1024];
    double r,theta,alpha,d;
    double x;
    struct expl_data cr_data;
    gsl_matrix *M;
    gsl_vector *V;
    gsl_permutation * p = gsl_permutation_alloc (6);
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    M=jac_explicit_t6( cr_data );
    V=DT7_explicit_t6( cr_data );
    error=gsl_linalg_LU_decomp(M,p,&sign);
    if(error !=GSL_SUCCESS) {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        sprintf(err_string,"GSL failing with error %d\n",error);
        failed(err_string);
    }
    x= gsl_linalg_LU_det(M,sign);
    if (fabs(x) < EPSIL_DET )
    {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_permutation_free(p);
        return -1;
    }else {
        gsl_vector_view  T_ = gsl_vector_subvector (T, 1, 6);
        error=gsl_linalg_LU_solve(M,p,V,&T_.vector);
        
        gsl_vector_set(T,0,gsl_vector_get(T,1));
        gsl_vector_set(T,1,gsl_vector_get(T,2));
        gsl_vector_set(T,2,gsl_vector_get(T,3));
        gsl_vector_set(T,3,gsl_vector_get(T,4));
        gsl_vector_set(T,4,gsl_vector_get(T,5));
        gsl_vector_set(T,5,-1);
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_vector_scale(T,-1.0);
        gsl_permutation_free(p);
        return error;
    }
}
int TmT7_t7(gsl_vector *T,const struct cr_input_data bb)
{
    int i,error, sign;
    char err_string[1024];
    double r,theta,alpha,d;
    double x;
    struct expl_data cr_data;
    gsl_matrix *M;
    gsl_vector *V;
    gsl_permutation * p = gsl_permutation_alloc (6);
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    M=jac_explicit_t7( cr_data );
    V=DT7_explicit_t7( cr_data );
    error=gsl_linalg_LU_decomp(M,p,&sign);
    if(error !=GSL_SUCCESS) {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        sprintf(err_string,"GSL failing with error %d\n",error);
        failed(err_string);
    }
    x= gsl_linalg_LU_det(M,sign);
    if (fabs(x) < EPSIL_DET )
    {
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_permutation_free(p);
        return -1;
    }else {
        gsl_vector_view  T_ = gsl_vector_subvector (T, 1, 6);
        error=gsl_linalg_LU_solve(M,p,V,&T_.vector);
        
        gsl_vector_set(T,0,gsl_vector_get(T,1));
        gsl_vector_set(T,1,gsl_vector_get(T,2));
        gsl_vector_set(T,2,gsl_vector_get(T,3));
        gsl_vector_set(T,3,gsl_vector_get(T,4));
        gsl_vector_set(T,4,gsl_vector_get(T,5));
        gsl_vector_set(T,5,gsl_vector_get(T,6));
        gsl_vector_set(T,6,-1);
        gsl_vector_free(V);
        gsl_matrix_free(M);
        gsl_vector_scale(T,-1.0);
        gsl_permutation_free(p);
        return error;
    }
}
gsl_vector * DT7_t1 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return DT7_explicit_t1(cr_data);
}
gsl_vector * DT7_t2 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return DT7_explicit_t2(cr_data);
}
gsl_vector * DT7_t3 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return DT7_explicit_t3(cr_data);
}
gsl_vector * DT7_t4 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return DT7_explicit_t4(cr_data);
}
gsl_vector * DT7_t5 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return DT7_explicit_t5(cr_data);
}
gsl_vector * DT7_t6 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return DT7_explicit_t6(cr_data);
}
gsl_vector * DT7_t7 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return DT7_explicit_t7(cr_data);
}
gsl_matrix * jac_t1 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return jac_explicit_t1(cr_data);
}
gsl_matrix * jac_t2 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return jac_explicit_t2(cr_data);
}
gsl_matrix * jac_t3 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return jac_explicit_t3(cr_data);
}
gsl_matrix * jac_t4 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return jac_explicit_t4(cr_data);
}
gsl_matrix * jac_t5 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return jac_explicit_t5(cr_data);
}
gsl_matrix * jac_t6 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return jac_explicit_t6(cr_data);
}
gsl_matrix * jac_t7 (const struct cr_input_data bb)
{
    int i;
    double r,theta,alpha,d;
    struct expl_data cr_data;
    for(i=0;i<7;i++)
    {
        r=gsl_vector_get(bb.r,i);
        theta=gsl_vector_get(bb.dihed_angles,i);
        alpha=gsl_vector_get(bb.bend_angles, i);
   
        cr_data.r[i] = r;
        cr_data.c[i] =cos(theta);
        cr_data.s[i] =sin(theta);
        cr_data.ca[i]=cos(alpha);
        cr_data.sa[i]=sin(alpha);
    }
    for(i=0;i<7;i++)
    {
        d=gsl_vector_get(bb.d,i);
        cr_data.d[i]=d;
    }
    return jac_explicit_t7(cr_data);
}

void T7_explicit (gsl_vector *T, struct expl_data cr_in)
{
    gsl_vector_set(T,0,get_T7_12(cr_in));
    gsl_vector_set(T,1,get_T7_13(cr_in));
    gsl_vector_set(T,2,get_T7_23(cr_in));
    gsl_vector_set(T,3,get_T7_14(cr_in));
    gsl_vector_set(T,4,get_T7_24(cr_in));
    gsl_vector_set(T,5,get_T7_34(cr_in));
}
    gsl_vector * DT7_explicit_t1 (struct expl_data cr_in)
{
	gsl_vector *t=gsl_vector_alloc(6);
	gsl_vector_set(t,0,get_DT7_t1_1(cr_in));
	gsl_vector_set(t,1,get_DT7_t1_2(cr_in));
	gsl_vector_set(t,2,get_DT7_t1_3(cr_in));
	gsl_vector_set(t,3,get_DT7_t1_4(cr_in));
	gsl_vector_set(t,4,get_DT7_t1_5(cr_in));
	gsl_vector_set(t,5,get_DT7_t1_6(cr_in));
	 return t;
}
gsl_vector * DT7_explicit_t2 (struct expl_data cr_in)
{
	gsl_vector *t=gsl_vector_alloc(6);
	gsl_vector_set(t,0,get_DT7_t2_1(cr_in));
	gsl_vector_set(t,1,get_DT7_t2_2(cr_in));
	gsl_vector_set(t,2,get_DT7_t2_3(cr_in));
	gsl_vector_set(t,3,get_DT7_t2_4(cr_in));
	gsl_vector_set(t,4,get_DT7_t2_5(cr_in));
	gsl_vector_set(t,5,get_DT7_t2_6(cr_in));
	 return t;
}
gsl_vector * DT7_explicit_t3 (struct expl_data cr_in)
{
	gsl_vector *t=gsl_vector_alloc(6);
	gsl_vector_set(t,0,get_DT7_t3_1(cr_in));
	gsl_vector_set(t,1,get_DT7_t3_2(cr_in));
	gsl_vector_set(t,2,get_DT7_t3_3(cr_in));
	gsl_vector_set(t,3,get_DT7_t3_4(cr_in));
	gsl_vector_set(t,4,get_DT7_t3_5(cr_in));
	gsl_vector_set(t,5,get_DT7_t3_6(cr_in));
	 return t;
}
gsl_vector * DT7_explicit_t4 (struct expl_data cr_in)
{
	gsl_vector *t=gsl_vector_alloc(6);
	gsl_vector_set(t,0,get_DT7_t4_1(cr_in));
	gsl_vector_set(t,1,get_DT7_t4_2(cr_in));
	gsl_vector_set(t,2,get_DT7_t4_3(cr_in));
	gsl_vector_set(t,3,get_DT7_t4_4(cr_in));
	gsl_vector_set(t,4,get_DT7_t4_5(cr_in));
	gsl_vector_set(t,5,get_DT7_t4_6(cr_in));
	 return t;
}
gsl_vector * DT7_explicit_t5 (struct expl_data cr_in)
{
	gsl_vector *t=gsl_vector_alloc(6);
	gsl_vector_set(t,0,get_DT7_t5_1(cr_in));
	gsl_vector_set(t,1,get_DT7_t5_2(cr_in));
	gsl_vector_set(t,2,get_DT7_t5_3(cr_in));
	gsl_vector_set(t,3,get_DT7_t5_4(cr_in));
	gsl_vector_set(t,4,get_DT7_t5_5(cr_in));
	gsl_vector_set(t,5,get_DT7_t5_6(cr_in));
	 return t;
}
gsl_vector * DT7_explicit_t6 (struct expl_data cr_in)
{
	gsl_vector *t=gsl_vector_alloc(6);
	gsl_vector_set(t,0,get_DT7_t6_1(cr_in));
	gsl_vector_set(t,1,get_DT7_t6_2(cr_in));
	gsl_vector_set(t,2,get_DT7_t6_3(cr_in));
	gsl_vector_set(t,3,get_DT7_t6_4(cr_in));
	gsl_vector_set(t,4,get_DT7_t6_5(cr_in));
	gsl_vector_set(t,5,get_DT7_t6_6(cr_in));
	 return t;
}
gsl_vector * DT7_explicit_t7 (struct expl_data cr_in)
{
	gsl_vector *t=gsl_vector_alloc(6);
	gsl_vector_set(t,0,get_DT7_t7_1(cr_in));
	gsl_vector_set(t,1,get_DT7_t7_2(cr_in));
	gsl_vector_set(t,2,get_DT7_t7_3(cr_in));
	gsl_vector_set(t,3,get_DT7_t7_4(cr_in));
	gsl_vector_set(t,4,get_DT7_t7_5(cr_in));
	gsl_vector_set(t,5,get_DT7_t7_6(cr_in));
	 return t;
}
gsl_matrix * jac_explicit_t1 (struct expl_data cr_in)
{
	gsl_matrix *m=gsl_matrix_alloc(6,6);
	//-- 
	gsl_matrix_set(m,0,0,get_jac_t1_11(cr_in));
	gsl_matrix_set(m,0,1,get_jac_t1_12(cr_in));
	gsl_matrix_set(m,0,2,get_jac_t1_13(cr_in));
	gsl_matrix_set(m,0,3,get_jac_t1_14(cr_in));
	gsl_matrix_set(m,0,4,get_jac_t1_15(cr_in));
	gsl_matrix_set(m,0,5,get_jac_t1_16(cr_in));
	//-- 
	gsl_matrix_set(m,1,0,get_jac_t1_21(cr_in));
	gsl_matrix_set(m,1,1,get_jac_t1_22(cr_in));
	gsl_matrix_set(m,1,2,get_jac_t1_23(cr_in));
	gsl_matrix_set(m,1,3,get_jac_t1_24(cr_in));
	gsl_matrix_set(m,1,4,get_jac_t1_25(cr_in));
	gsl_matrix_set(m,1,5,get_jac_t1_26(cr_in));
	//-- 
	gsl_matrix_set(m,2,0,get_jac_t1_31(cr_in));
	gsl_matrix_set(m,2,1,get_jac_t1_32(cr_in));
	gsl_matrix_set(m,2,2,get_jac_t1_33(cr_in));
	gsl_matrix_set(m,2,3,get_jac_t1_34(cr_in));
	gsl_matrix_set(m,2,4,get_jac_t1_35(cr_in));
	gsl_matrix_set(m,2,5,get_jac_t1_36(cr_in));
	//-- 
	gsl_matrix_set(m,3,0,get_jac_t1_41(cr_in));
	gsl_matrix_set(m,3,1,get_jac_t1_42(cr_in));
	gsl_matrix_set(m,3,2,get_jac_t1_43(cr_in));
	gsl_matrix_set(m,3,3,get_jac_t1_44(cr_in));
	gsl_matrix_set(m,3,4,get_jac_t1_45(cr_in));
	gsl_matrix_set(m,3,5,get_jac_t1_46(cr_in));
	//-- 
	gsl_matrix_set(m,4,0,get_jac_t1_51(cr_in));
	gsl_matrix_set(m,4,1,get_jac_t1_52(cr_in));
	gsl_matrix_set(m,4,2,get_jac_t1_53(cr_in));
	gsl_matrix_set(m,4,3,get_jac_t1_54(cr_in));
	gsl_matrix_set(m,4,4,get_jac_t1_55(cr_in));
	gsl_matrix_set(m,4,5,get_jac_t1_56(cr_in));
	//-- 
	gsl_matrix_set(m,5,0,get_jac_t1_61(cr_in));
	gsl_matrix_set(m,5,1,get_jac_t1_62(cr_in));
	gsl_matrix_set(m,5,2,get_jac_t1_63(cr_in));
	gsl_matrix_set(m,5,3,get_jac_t1_64(cr_in));
	gsl_matrix_set(m,5,4,get_jac_t1_65(cr_in));
	gsl_matrix_set(m,5,5,get_jac_t1_66(cr_in));
	return m;
}
gsl_matrix * jac_explicit_t2 (struct expl_data cr_in)
{
	gsl_matrix *m=gsl_matrix_alloc(6,6);
	//-- 
	gsl_matrix_set(m,0,0,get_jac_t2_11(cr_in));
	gsl_matrix_set(m,0,1,get_jac_t2_12(cr_in));
	gsl_matrix_set(m,0,2,get_jac_t2_13(cr_in));
	gsl_matrix_set(m,0,3,get_jac_t2_14(cr_in));
	gsl_matrix_set(m,0,4,get_jac_t2_15(cr_in));
	gsl_matrix_set(m,0,5,get_jac_t2_16(cr_in));
	//-- 
	gsl_matrix_set(m,1,0,get_jac_t2_21(cr_in));
	gsl_matrix_set(m,1,1,get_jac_t2_22(cr_in));
	gsl_matrix_set(m,1,2,get_jac_t2_23(cr_in));
	gsl_matrix_set(m,1,3,get_jac_t2_24(cr_in));
	gsl_matrix_set(m,1,4,get_jac_t2_25(cr_in));
	gsl_matrix_set(m,1,5,get_jac_t2_26(cr_in));
	//-- 
	gsl_matrix_set(m,2,0,get_jac_t2_31(cr_in));
	gsl_matrix_set(m,2,1,get_jac_t2_32(cr_in));
	gsl_matrix_set(m,2,2,get_jac_t2_33(cr_in));
	gsl_matrix_set(m,2,3,get_jac_t2_34(cr_in));
	gsl_matrix_set(m,2,4,get_jac_t2_35(cr_in));
	gsl_matrix_set(m,2,5,get_jac_t2_36(cr_in));
	//-- 
	gsl_matrix_set(m,3,0,get_jac_t2_41(cr_in));
	gsl_matrix_set(m,3,1,get_jac_t2_42(cr_in));
	gsl_matrix_set(m,3,2,get_jac_t2_43(cr_in));
	gsl_matrix_set(m,3,3,get_jac_t2_44(cr_in));
	gsl_matrix_set(m,3,4,get_jac_t2_45(cr_in));
	gsl_matrix_set(m,3,5,get_jac_t2_46(cr_in));
	//-- 
	gsl_matrix_set(m,4,0,get_jac_t2_51(cr_in));
	gsl_matrix_set(m,4,1,get_jac_t2_52(cr_in));
	gsl_matrix_set(m,4,2,get_jac_t2_53(cr_in));
	gsl_matrix_set(m,4,3,get_jac_t2_54(cr_in));
	gsl_matrix_set(m,4,4,get_jac_t2_55(cr_in));
	gsl_matrix_set(m,4,5,get_jac_t2_56(cr_in));
	//-- 
	gsl_matrix_set(m,5,0,get_jac_t2_61(cr_in));
	gsl_matrix_set(m,5,1,get_jac_t2_62(cr_in));
	gsl_matrix_set(m,5,2,get_jac_t2_63(cr_in));
	gsl_matrix_set(m,5,3,get_jac_t2_64(cr_in));
	gsl_matrix_set(m,5,4,get_jac_t2_65(cr_in));
	gsl_matrix_set(m,5,5,get_jac_t2_66(cr_in));
	return m;
}
gsl_matrix * jac_explicit_t3 (struct expl_data cr_in)
{
	gsl_matrix *m=gsl_matrix_alloc(6,6);
	//-- 
	gsl_matrix_set(m,0,0,get_jac_t3_11(cr_in));
	gsl_matrix_set(m,0,1,get_jac_t3_12(cr_in));
	gsl_matrix_set(m,0,2,get_jac_t3_13(cr_in));
	gsl_matrix_set(m,0,3,get_jac_t3_14(cr_in));
	gsl_matrix_set(m,0,4,get_jac_t3_15(cr_in));
	gsl_matrix_set(m,0,5,get_jac_t3_16(cr_in));
	//-- 
	gsl_matrix_set(m,1,0,get_jac_t3_21(cr_in));
	gsl_matrix_set(m,1,1,get_jac_t3_22(cr_in));
	gsl_matrix_set(m,1,2,get_jac_t3_23(cr_in));
	gsl_matrix_set(m,1,3,get_jac_t3_24(cr_in));
	gsl_matrix_set(m,1,4,get_jac_t3_25(cr_in));
	gsl_matrix_set(m,1,5,get_jac_t3_26(cr_in));
	//-- 
	gsl_matrix_set(m,2,0,get_jac_t3_31(cr_in));
	gsl_matrix_set(m,2,1,get_jac_t3_32(cr_in));
	gsl_matrix_set(m,2,2,get_jac_t3_33(cr_in));
	gsl_matrix_set(m,2,3,get_jac_t3_34(cr_in));
	gsl_matrix_set(m,2,4,get_jac_t3_35(cr_in));
	gsl_matrix_set(m,2,5,get_jac_t3_36(cr_in));
	//-- 
	gsl_matrix_set(m,3,0,get_jac_t3_41(cr_in));
	gsl_matrix_set(m,3,1,get_jac_t3_42(cr_in));
	gsl_matrix_set(m,3,2,get_jac_t3_43(cr_in));
	gsl_matrix_set(m,3,3,get_jac_t3_44(cr_in));
	gsl_matrix_set(m,3,4,get_jac_t3_45(cr_in));
	gsl_matrix_set(m,3,5,get_jac_t3_46(cr_in));
	//-- 
	gsl_matrix_set(m,4,0,get_jac_t3_51(cr_in));
	gsl_matrix_set(m,4,1,get_jac_t3_52(cr_in));
	gsl_matrix_set(m,4,2,get_jac_t3_53(cr_in));
	gsl_matrix_set(m,4,3,get_jac_t3_54(cr_in));
	gsl_matrix_set(m,4,4,get_jac_t3_55(cr_in));
	gsl_matrix_set(m,4,5,get_jac_t3_56(cr_in));
	//-- 
	gsl_matrix_set(m,5,0,get_jac_t3_61(cr_in));
	gsl_matrix_set(m,5,1,get_jac_t3_62(cr_in));
	gsl_matrix_set(m,5,2,get_jac_t3_63(cr_in));
	gsl_matrix_set(m,5,3,get_jac_t3_64(cr_in));
	gsl_matrix_set(m,5,4,get_jac_t3_65(cr_in));
	gsl_matrix_set(m,5,5,get_jac_t3_66(cr_in));
	return m;
}
gsl_matrix * jac_explicit_t4 (struct expl_data cr_in)
{
	gsl_matrix *m=gsl_matrix_alloc(6,6);
	//-- 
	gsl_matrix_set(m,0,0,get_jac_t4_11(cr_in));
	gsl_matrix_set(m,0,1,get_jac_t4_12(cr_in));
	gsl_matrix_set(m,0,2,get_jac_t4_13(cr_in));
	gsl_matrix_set(m,0,3,get_jac_t4_14(cr_in));
	gsl_matrix_set(m,0,4,get_jac_t4_15(cr_in));
	gsl_matrix_set(m,0,5,get_jac_t4_16(cr_in));
	//-- 
	gsl_matrix_set(m,1,0,get_jac_t4_21(cr_in));
	gsl_matrix_set(m,1,1,get_jac_t4_22(cr_in));
	gsl_matrix_set(m,1,2,get_jac_t4_23(cr_in));
	gsl_matrix_set(m,1,3,get_jac_t4_24(cr_in));
	gsl_matrix_set(m,1,4,get_jac_t4_25(cr_in));
	gsl_matrix_set(m,1,5,get_jac_t4_26(cr_in));
	//-- 
	gsl_matrix_set(m,2,0,get_jac_t4_31(cr_in));
	gsl_matrix_set(m,2,1,get_jac_t4_32(cr_in));
	gsl_matrix_set(m,2,2,get_jac_t4_33(cr_in));
	gsl_matrix_set(m,2,3,get_jac_t4_34(cr_in));
	gsl_matrix_set(m,2,4,get_jac_t4_35(cr_in));
	gsl_matrix_set(m,2,5,get_jac_t4_36(cr_in));
	//-- 
	gsl_matrix_set(m,3,0,get_jac_t4_41(cr_in));
	gsl_matrix_set(m,3,1,get_jac_t4_42(cr_in));
	gsl_matrix_set(m,3,2,get_jac_t4_43(cr_in));
	gsl_matrix_set(m,3,3,get_jac_t4_44(cr_in));
	gsl_matrix_set(m,3,4,get_jac_t4_45(cr_in));
	gsl_matrix_set(m,3,5,get_jac_t4_46(cr_in));
	//-- 
	gsl_matrix_set(m,4,0,get_jac_t4_51(cr_in));
	gsl_matrix_set(m,4,1,get_jac_t4_52(cr_in));
	gsl_matrix_set(m,4,2,get_jac_t4_53(cr_in));
	gsl_matrix_set(m,4,3,get_jac_t4_54(cr_in));
	gsl_matrix_set(m,4,4,get_jac_t4_55(cr_in));
	gsl_matrix_set(m,4,5,get_jac_t4_56(cr_in));
	//-- 
	gsl_matrix_set(m,5,0,get_jac_t4_61(cr_in));
	gsl_matrix_set(m,5,1,get_jac_t4_62(cr_in));
	gsl_matrix_set(m,5,2,get_jac_t4_63(cr_in));
	gsl_matrix_set(m,5,3,get_jac_t4_64(cr_in));
	gsl_matrix_set(m,5,4,get_jac_t4_65(cr_in));
	gsl_matrix_set(m,5,5,get_jac_t4_66(cr_in));
	return m;
}
gsl_matrix * jac_explicit_t5 (struct expl_data cr_in)
{
	gsl_matrix *m=gsl_matrix_alloc(6,6);
	//-- 
	gsl_matrix_set(m,0,0,get_jac_t5_11(cr_in));
	gsl_matrix_set(m,0,1,get_jac_t5_12(cr_in));
	gsl_matrix_set(m,0,2,get_jac_t5_13(cr_in));
	gsl_matrix_set(m,0,3,get_jac_t5_14(cr_in));
	gsl_matrix_set(m,0,4,get_jac_t5_15(cr_in));
	gsl_matrix_set(m,0,5,get_jac_t5_16(cr_in));
	//-- 
	gsl_matrix_set(m,1,0,get_jac_t5_21(cr_in));
	gsl_matrix_set(m,1,1,get_jac_t5_22(cr_in));
	gsl_matrix_set(m,1,2,get_jac_t5_23(cr_in));
	gsl_matrix_set(m,1,3,get_jac_t5_24(cr_in));
	gsl_matrix_set(m,1,4,get_jac_t5_25(cr_in));
	gsl_matrix_set(m,1,5,get_jac_t5_26(cr_in));
	//-- 
	gsl_matrix_set(m,2,0,get_jac_t5_31(cr_in));
	gsl_matrix_set(m,2,1,get_jac_t5_32(cr_in));
	gsl_matrix_set(m,2,2,get_jac_t5_33(cr_in));
	gsl_matrix_set(m,2,3,get_jac_t5_34(cr_in));
	gsl_matrix_set(m,2,4,get_jac_t5_35(cr_in));
	gsl_matrix_set(m,2,5,get_jac_t5_36(cr_in));
	//-- 
	gsl_matrix_set(m,3,0,get_jac_t5_41(cr_in));
	gsl_matrix_set(m,3,1,get_jac_t5_42(cr_in));
	gsl_matrix_set(m,3,2,get_jac_t5_43(cr_in));
	gsl_matrix_set(m,3,3,get_jac_t5_44(cr_in));
	gsl_matrix_set(m,3,4,get_jac_t5_45(cr_in));
	gsl_matrix_set(m,3,5,get_jac_t5_46(cr_in));
	//-- 
	gsl_matrix_set(m,4,0,get_jac_t5_51(cr_in));
	gsl_matrix_set(m,4,1,get_jac_t5_52(cr_in));
	gsl_matrix_set(m,4,2,get_jac_t5_53(cr_in));
	gsl_matrix_set(m,4,3,get_jac_t5_54(cr_in));
	gsl_matrix_set(m,4,4,get_jac_t5_55(cr_in));
	gsl_matrix_set(m,4,5,get_jac_t5_56(cr_in));
	//-- 
	gsl_matrix_set(m,5,0,get_jac_t5_61(cr_in));
	gsl_matrix_set(m,5,1,get_jac_t5_62(cr_in));
	gsl_matrix_set(m,5,2,get_jac_t5_63(cr_in));
	gsl_matrix_set(m,5,3,get_jac_t5_64(cr_in));
	gsl_matrix_set(m,5,4,get_jac_t5_65(cr_in));
	gsl_matrix_set(m,5,5,get_jac_t5_66(cr_in));
	return m;
}
gsl_matrix * jac_explicit_t6 (struct expl_data cr_in)
{
	gsl_matrix *m=gsl_matrix_alloc(6,6);
	//-- 
	gsl_matrix_set(m,0,0,get_jac_t6_11(cr_in));
	gsl_matrix_set(m,0,1,get_jac_t6_12(cr_in));
	gsl_matrix_set(m,0,2,get_jac_t6_13(cr_in));
	gsl_matrix_set(m,0,3,get_jac_t6_14(cr_in));
	gsl_matrix_set(m,0,4,get_jac_t6_15(cr_in));
	gsl_matrix_set(m,0,5,get_jac_t6_16(cr_in));
	//-- 
	gsl_matrix_set(m,1,0,get_jac_t6_21(cr_in));
	gsl_matrix_set(m,1,1,get_jac_t6_22(cr_in));
	gsl_matrix_set(m,1,2,get_jac_t6_23(cr_in));
	gsl_matrix_set(m,1,3,get_jac_t6_24(cr_in));
	gsl_matrix_set(m,1,4,get_jac_t6_25(cr_in));
	gsl_matrix_set(m,1,5,get_jac_t6_26(cr_in));
	//-- 
	gsl_matrix_set(m,2,0,get_jac_t6_31(cr_in));
	gsl_matrix_set(m,2,1,get_jac_t6_32(cr_in));
	gsl_matrix_set(m,2,2,get_jac_t6_33(cr_in));
	gsl_matrix_set(m,2,3,get_jac_t6_34(cr_in));
	gsl_matrix_set(m,2,4,get_jac_t6_35(cr_in));
	gsl_matrix_set(m,2,5,get_jac_t6_36(cr_in));
	//-- 
	gsl_matrix_set(m,3,0,get_jac_t6_41(cr_in));
	gsl_matrix_set(m,3,1,get_jac_t6_42(cr_in));
	gsl_matrix_set(m,3,2,get_jac_t6_43(cr_in));
	gsl_matrix_set(m,3,3,get_jac_t6_44(cr_in));
	gsl_matrix_set(m,3,4,get_jac_t6_45(cr_in));
	gsl_matrix_set(m,3,5,get_jac_t6_46(cr_in));
	//-- 
	gsl_matrix_set(m,4,0,get_jac_t6_51(cr_in));
	gsl_matrix_set(m,4,1,get_jac_t6_52(cr_in));
	gsl_matrix_set(m,4,2,get_jac_t6_53(cr_in));
	gsl_matrix_set(m,4,3,get_jac_t6_54(cr_in));
	gsl_matrix_set(m,4,4,get_jac_t6_55(cr_in));
	gsl_matrix_set(m,4,5,get_jac_t6_56(cr_in));
	//-- 
	gsl_matrix_set(m,5,0,get_jac_t6_61(cr_in));
	gsl_matrix_set(m,5,1,get_jac_t6_62(cr_in));
	gsl_matrix_set(m,5,2,get_jac_t6_63(cr_in));
	gsl_matrix_set(m,5,3,get_jac_t6_64(cr_in));
	gsl_matrix_set(m,5,4,get_jac_t6_65(cr_in));
	gsl_matrix_set(m,5,5,get_jac_t6_66(cr_in));
	return m;
}
gsl_matrix * jac_explicit_t7 (struct expl_data cr_in)
{
	gsl_matrix *m=gsl_matrix_alloc(6,6);
	//-- 
	gsl_matrix_set(m,0,0,get_jac_t7_11(cr_in));
	gsl_matrix_set(m,0,1,get_jac_t7_12(cr_in));
	gsl_matrix_set(m,0,2,get_jac_t7_13(cr_in));
	gsl_matrix_set(m,0,3,get_jac_t7_14(cr_in));
	gsl_matrix_set(m,0,4,get_jac_t7_15(cr_in));
	gsl_matrix_set(m,0,5,get_jac_t7_16(cr_in));
	//-- 
	gsl_matrix_set(m,1,0,get_jac_t7_21(cr_in));
	gsl_matrix_set(m,1,1,get_jac_t7_22(cr_in));
	gsl_matrix_set(m,1,2,get_jac_t7_23(cr_in));
	gsl_matrix_set(m,1,3,get_jac_t7_24(cr_in));
	gsl_matrix_set(m,1,4,get_jac_t7_25(cr_in));
	gsl_matrix_set(m,1,5,get_jac_t7_26(cr_in));
	//-- 
	gsl_matrix_set(m,2,0,get_jac_t7_31(cr_in));
	gsl_matrix_set(m,2,1,get_jac_t7_32(cr_in));
	gsl_matrix_set(m,2,2,get_jac_t7_33(cr_in));
	gsl_matrix_set(m,2,3,get_jac_t7_34(cr_in));
	gsl_matrix_set(m,2,4,get_jac_t7_35(cr_in));
	gsl_matrix_set(m,2,5,get_jac_t7_36(cr_in));
	//-- 
	gsl_matrix_set(m,3,0,get_jac_t7_41(cr_in));
	gsl_matrix_set(m,3,1,get_jac_t7_42(cr_in));
	gsl_matrix_set(m,3,2,get_jac_t7_43(cr_in));
	gsl_matrix_set(m,3,3,get_jac_t7_44(cr_in));
	gsl_matrix_set(m,3,4,get_jac_t7_45(cr_in));
	gsl_matrix_set(m,3,5,get_jac_t7_46(cr_in));
	//-- 
	gsl_matrix_set(m,4,0,get_jac_t7_51(cr_in));
	gsl_matrix_set(m,4,1,get_jac_t7_52(cr_in));
	gsl_matrix_set(m,4,2,get_jac_t7_53(cr_in));
	gsl_matrix_set(m,4,3,get_jac_t7_54(cr_in));
	gsl_matrix_set(m,4,4,get_jac_t7_55(cr_in));
	gsl_matrix_set(m,4,5,get_jac_t7_56(cr_in));
	//-- 
	gsl_matrix_set(m,5,0,get_jac_t7_61(cr_in));
	gsl_matrix_set(m,5,1,get_jac_t7_62(cr_in));
	gsl_matrix_set(m,5,2,get_jac_t7_63(cr_in));
	gsl_matrix_set(m,5,3,get_jac_t7_64(cr_in));
	gsl_matrix_set(m,5,4,get_jac_t7_65(cr_in));
	gsl_matrix_set(m,5,5,get_jac_t7_66(cr_in));
	return m;
}
