#!/bin/bash

if [ ! -f ./plotFunctions ]; then
    echo "Missing plotFunctions!"
    return 1;
fi
source ./plotFunctions
### How many separate simulations are run to get better statistics?
RUNS=5
###

if [ ! -d TEST ]; then
    mkdir TEST
fi

if [ ! -f ./test_CR_speed.x ]; then
    echo "Missing compiled program test_CR_speed.x !"
    return 1;
fi

if [ ! -f ./run ]; then
    echo "Missing run script!"
    return 1;
fi


cd TEST
for i in $(seq 0 1 ${RUNS}); do
    ## might be better to have random number in run#randomNumber# so we do not repeat simulation with same random number
    if [ ! -d run${i} ]; then
	mkdir run${i}
	echo ${i}
	cp ../test_CR_speed.x ../run run${i}/
	cd run${i}
	## stuff for either running simulation or for submiting to clusters
	psubmit default run props=kraken -y
	cd ../
    fi
done

####### NOW we print out data ... in grpahs etc.
#rmachandran #we do not sample phi-psi histogram ... any more
graphs
